[build]
  base    = "frontend"
  publish = "frontend/dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Optional: set Node version to avoid mismatches
[build.environment]
  NODE_VERSION = "20"
