# Netlify Configuration File
# Complete configuration for HAP-EB Application

[build]
  # Build command to run
  command = "npm ci && npm run build"
  
  # Directory containing Netlify Functions
  functions = "netlify/functions"
  
  # Directory to publish (build output)
  publish = "dist"

# Edge Functions configuration
[[edge_functions]]
path = "/master-admin"
function = "master-admin"

[[edge_functions]]
path = "/admin"
function = "admin"

[[edge_functions]]
path = "/tl"
function = "tl"

[[edge_functions]]
path = "/msp"
function = "msp"
