[build]
  base = "frontend"
  publish = "frontend/dist"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[scheduled]]
  path = "/api/reports_cron"
  schedule = "0 2 * * 1"
